package objects;

// Generated Jul 17, 2015 7:51:51 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * FoodCategory generated by hbm2java
 */
public class FoodCategory implements java.io.Serializable {

	private Integer idFoodCategory;
	private String name;
	private String description;
	private String urlImage;
	private Set foods = new HashSet(0);

	public FoodCategory() {
	}

	public FoodCategory(String name, String description, String urlImage) {
		this.name = name;
		this.description = description;
		this.urlImage = urlImage;
	}

	public FoodCategory(String name, String description, String urlImage,
			Set foods) {
		this.name = name;
		this.description = description;
		this.urlImage = urlImage;
		this.foods = foods;
	}

	public Integer getIdFoodCategory() {
		return this.idFoodCategory;
	}

	public void setIdFoodCategory(Integer idFoodCategory) {
		this.idFoodCategory = idFoodCategory;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getUrlImage() {
		return this.urlImage;
	}

	public void setUrlImage(String urlImage) {
		this.urlImage = urlImage;
	}

	public Set getFoods() {
		return this.foods;
	}

	public void setFoods(Set foods) {
		this.foods = foods;
	}

}
