// default package
// Generated Jul 17, 2015 5:10:27 PM by Hibernate Tools 4.3.1
package objects;
/**
 * FoodId generated by hbm2java
 */
public class FoodId implements java.io.Serializable {

	private int idFood;
	private int idFoodCategory;

	public FoodId() {
	}

	public FoodId(int idFood, int idFoodCategory) {
		this.idFood = idFood;
		this.idFoodCategory = idFoodCategory;
	}

	public int getIdFood() {
		return this.idFood;
	}

	public void setIdFood(int idFood) {
		this.idFood = idFood;
	}

	public int getIdFoodCategory() {
		return this.idFoodCategory;
	}

	public void setIdFoodCategory(int idFoodCategory) {
		this.idFoodCategory = idFoodCategory;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof FoodId))
			return false;
		FoodId castOther = (FoodId) other;

		return (this.getIdFood() == castOther.getIdFood())
				&& (this.getIdFoodCategory() == castOther.getIdFoodCategory());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdFood();
		result = 37 * result + this.getIdFoodCategory();
		return result;
	}

}
