// default package
// Generated Jul 17, 2015 5:10:27 PM by Hibernate Tools 4.3.1
package objects;
import java.util.Date;

/**
 * Foods generated by hbm2java
 */
public class Foods implements java.io.Serializable {

	private Integer id;
	private String name;
	private String nameScientific;
	private String description;
	private String itisId;
	private String wikipediaId;
	private String pictureFileName;
	private String pictureContentType;
	private Integer pictureFileSize;
	private Date pictureUpdatedAt;
	private Integer legacyId;
	private String foodGroup;
	private String foodSubgroup;
	private String foodType;
	private Date createdAt;
	private Date updatedAt;
	private Integer creatorId;
	private Integer updaterId;

	public Foods() {
	}

	public Foods(String name, String foodType) {
		this.name = name;
		this.foodType = foodType;
	}

	public Foods(String name, String nameScientific, String description,
			String itisId, String wikipediaId, String pictureFileName,
			String pictureContentType, Integer pictureFileSize,
			Date pictureUpdatedAt, Integer legacyId, String foodGroup,
			String foodSubgroup, String foodType, Date createdAt,
			Date updatedAt, Integer creatorId, Integer updaterId) {
		this.name = name;
		this.nameScientific = nameScientific;
		this.description = description;
		this.itisId = itisId;
		this.wikipediaId = wikipediaId;
		this.pictureFileName = pictureFileName;
		this.pictureContentType = pictureContentType;
		this.pictureFileSize = pictureFileSize;
		this.pictureUpdatedAt = pictureUpdatedAt;
		this.legacyId = legacyId;
		this.foodGroup = foodGroup;
		this.foodSubgroup = foodSubgroup;
		this.foodType = foodType;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.creatorId = creatorId;
		this.updaterId = updaterId;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getNameScientific() {
		return this.nameScientific;
	}

	public void setNameScientific(String nameScientific) {
		this.nameScientific = nameScientific;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getItisId() {
		return this.itisId;
	}

	public void setItisId(String itisId) {
		this.itisId = itisId;
	}

	public String getWikipediaId() {
		return this.wikipediaId;
	}

	public void setWikipediaId(String wikipediaId) {
		this.wikipediaId = wikipediaId;
	}

	public String getPictureFileName() {
		return this.pictureFileName;
	}

	public void setPictureFileName(String pictureFileName) {
		this.pictureFileName = pictureFileName;
	}

	public String getPictureContentType() {
		return this.pictureContentType;
	}

	public void setPictureContentType(String pictureContentType) {
		this.pictureContentType = pictureContentType;
	}

	public Integer getPictureFileSize() {
		return this.pictureFileSize;
	}

	public void setPictureFileSize(Integer pictureFileSize) {
		this.pictureFileSize = pictureFileSize;
	}

	public Date getPictureUpdatedAt() {
		return this.pictureUpdatedAt;
	}

	public void setPictureUpdatedAt(Date pictureUpdatedAt) {
		this.pictureUpdatedAt = pictureUpdatedAt;
	}

	public Integer getLegacyId() {
		return this.legacyId;
	}

	public void setLegacyId(Integer legacyId) {
		this.legacyId = legacyId;
	}

	public String getFoodGroup() {
		return this.foodGroup;
	}

	public void setFoodGroup(String foodGroup) {
		this.foodGroup = foodGroup;
	}

	public String getFoodSubgroup() {
		return this.foodSubgroup;
	}

	public void setFoodSubgroup(String foodSubgroup) {
		this.foodSubgroup = foodSubgroup;
	}

	public String getFoodType() {
		return this.foodType;
	}

	public void setFoodType(String foodType) {
		this.foodType = foodType;
	}

	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	public Integer getCreatorId() {
		return this.creatorId;
	}

	public void setCreatorId(Integer creatorId) {
		this.creatorId = creatorId;
	}

	public Integer getUpdaterId() {
		return this.updaterId;
	}

	public void setUpdaterId(Integer updaterId) {
		this.updaterId = updaterId;
	}

}
