// default package
// Generated Jul 17, 2015 5:10:27 PM by Hibernate Tools 4.3.1
package objects;
import java.util.HashSet;
import java.util.Set;

/**
 * Food generated by hbm2java
 */
public class Food implements java.io.Serializable {

	private FoodId id;
	private FoodCategory foodCategory;
	private String name;
	private String description;
	private String urlImage;
	private float price;
	private Set remainingFoods = new HashSet(0);
	private Set orderedItems = new HashSet(0);

	public Food() {
	}

	public Food(FoodId id, FoodCategory foodCategory, String name,
			String description, String urlImage, float price) {
		this.id = id;
		this.foodCategory = foodCategory;
		this.name = name;
		this.description = description;
		this.urlImage = urlImage;
		this.price = price;
	}

	public Food(FoodId id, FoodCategory foodCategory, String name,
			String description, String urlImage, float price,
			Set remainingFoods, Set orderedItems) {
		this.id = id;
		this.foodCategory = foodCategory;
		this.name = name;
		this.description = description;
		this.urlImage = urlImage;
		this.price = price;
		this.remainingFoods = remainingFoods;
		this.orderedItems = orderedItems;
	}

	public FoodId getId() {
		return this.id;
	}

	public void setId(FoodId id) {
		this.id = id;
	}

	public FoodCategory getFoodCategory() {
		return this.foodCategory;
	}

	public void setFoodCategory(FoodCategory foodCategory) {
		this.foodCategory = foodCategory;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getUrlImage() {
		return this.urlImage;
	}

	public void setUrlImage(String urlImage) {
		this.urlImage = urlImage;
	}

	public float getPrice() {
		return this.price;
	}

	public void setPrice(float price) {
		this.price = price;
	}

	public Set getRemainingFoods() {
		return this.remainingFoods;
	}

	public void setRemainingFoods(Set remainingFoods) {
		this.remainingFoods = remainingFoods;
	}

	public Set getOrderedItems() {
		return this.orderedItems;
	}

	public void setOrderedItems(Set orderedItems) {
		this.orderedItems = orderedItems;
	}

}
