package objects;

// Generated Jul 17, 2015 12:09:18 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Group generated by hbm2java
 */
public class Group implements java.io.Serializable {

	private int idGroup;
	private String name;
	private Set refrigerators = new HashSet(0);
	private Set users = new HashSet(0);

	public Group() {
	}

	public Group(int idGroup) {
		this.idGroup = idGroup;
	}

	public Group(int idGroup, String name, Set refrigerators, Set users) {
		this.idGroup = idGroup;
		this.name = name;
		this.refrigerators = refrigerators;
		this.users = users;
	}

	public int getIdGroup() {
		return this.idGroup;
	}

	public void setIdGroup(int idGroup) {
		this.idGroup = idGroup;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set getRefrigerators() {
		return this.refrigerators;
	}

	public void setRefrigerators(Set refrigerators) {
		this.refrigerators = refrigerators;
	}

	public Set getUsers() {
		return this.users;
	}

	public void setUsers(Set users) {
		this.users = users;
	}

}
