package objects;
// default package
// Generated Jul 3, 2015 10:47:01 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Note generated by hbm2java
 */
public class Note implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5837551094967962731L;
	public static final String NOTES_NOT_RD_LBL = "note_not_read";
	private Integer idNote;
	private String content;
	private Date date;
	private Set sharedNoteses = new HashSet(0);

	public Note() {
	}

	public Note(String content, Date date) {
		this.content = content;
		this.date = date;
	}

	public Note(String content, Date date, Set sharedNoteses) {
		this.content = content;
		this.date = date;
		this.sharedNoteses = sharedNoteses;
	}

	public Integer getIdNote() {
		return this.idNote;
	}

	public void setIdNote(Integer idNote) {
		this.idNote = idNote;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public Set getSharedNoteses() {
		return this.sharedNoteses;
	}

	public void setSharedNoteses(Set sharedNoteses) {
		this.sharedNoteses = sharedNoteses;
	}

}
