package objects;

// Generated Jul 8, 2015 3:09:09 PM by Hibernate Tools 4.3.1

/**
 * OrderedItemId generated by hbm2java
 */
public class OrderedItemId implements java.io.Serializable {

	private int idOrder;
	private int idFood;

	public OrderedItemId() {
	}

	public OrderedItemId(int idOrder, int idFood) {
		this.idOrder = idOrder;
		this.idFood = idFood;
	}

	public int getIdOrder() {
		return this.idOrder;
	}

	public void setIdOrder(int idOrder) {
		this.idOrder = idOrder;
	}

	public int getIdFood() {
		return this.idFood;
	}

	public void setIdFood(int idFood) {
		this.idFood = idFood;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof OrderedItemId))
			return false;
		OrderedItemId castOther = (OrderedItemId) other;

		return (this.getIdOrder() == castOther.getIdOrder())
				&& (this.getIdFood() == castOther.getIdFood());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdOrder();
		result = 37 * result + this.getIdFood();
		return result;
	}

}
