package objects;

// Generated Jul 17, 2015 12:09:18 PM by Hibernate Tools 4.3.1

/**
 * OrderId generated by hbm2java
 */
public class OrderId implements java.io.Serializable {

	private int idOrder;
	private int idGroup;
	private int idUser;

	public OrderId() {
	}

	public OrderId(int idOrder, int idGroup, int idUser) {
		this.idOrder = idOrder;
		this.idGroup = idGroup;
		this.idUser = idUser;
	}

	public int getIdOrder() {
		return this.idOrder;
	}

	public void setIdOrder(int idOrder) {
		this.idOrder = idOrder;
	}

	public int getIdGroup() {
		return this.idGroup;
	}

	public void setIdGroup(int idGroup) {
		this.idGroup = idGroup;
	}

	public int getIdUser() {
		return this.idUser;
	}

	public void setIdUser(int idUser) {
		this.idUser = idUser;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof OrderId))
			return false;
		OrderId castOther = (OrderId) other;

		return (this.getIdOrder() == castOther.getIdOrder())
				&& (this.getIdGroup() == castOther.getIdGroup())
				&& (this.getIdUser() == castOther.getIdUser());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdOrder();
		result = 37 * result + this.getIdGroup();
		result = 37 * result + this.getIdUser();
		return result;
	}

}
