// default package
// Generated Jul 17, 2015 5:10:27 PM by Hibernate Tools 4.3.1
package objects;
/**
 * OrderedItemId generated by hbm2java
 */
public class OrderedItemId implements java.io.Serializable {

	private int idFood;
	private int idFoodCategory;
	private int idOrder;
	private int idGroup;
	private int idUser;

	public OrderedItemId() {
	}

	public OrderedItemId(int idFood, int idFoodCategory, int idOrder,
			int idGroup, int idUser) {
		this.idFood = idFood;
		this.idFoodCategory = idFoodCategory;
		this.idOrder = idOrder;
		this.idGroup = idGroup;
		this.idUser = idUser;
	}

	public int getIdFood() {
		return this.idFood;
	}

	public void setIdFood(int idFood) {
		this.idFood = idFood;
	}

	public int getIdFoodCategory() {
		return this.idFoodCategory;
	}

	public void setIdFoodCategory(int idFoodCategory) {
		this.idFoodCategory = idFoodCategory;
	}

	public int getIdOrder() {
		return this.idOrder;
	}

	public void setIdOrder(int idOrder) {
		this.idOrder = idOrder;
	}

	public int getIdGroup() {
		return this.idGroup;
	}

	public void setIdGroup(int idGroup) {
		this.idGroup = idGroup;
	}

	public int getIdUser() {
		return this.idUser;
	}

	public void setIdUser(int idUser) {
		this.idUser = idUser;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof OrderedItemId))
			return false;
		OrderedItemId castOther = (OrderedItemId) other;

		return (this.getIdFood() == castOther.getIdFood())
				&& (this.getIdFoodCategory() == castOther.getIdFoodCategory())
				&& (this.getIdOrder() == castOther.getIdOrder())
				&& (this.getIdGroup() == castOther.getIdGroup())
				&& (this.getIdUser() == castOther.getIdUser());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdFood();
		result = 37 * result + this.getIdFoodCategory();
		result = 37 * result + this.getIdOrder();
		result = 37 * result + this.getIdGroup();
		result = 37 * result + this.getIdUser();
		return result;
	}

}
