package objects;

// Generated Jul 22, 2015 3:20:37 PM by Hibernate Tools 4.3.1

/**
 * RecipeFood generated by hbm2java
 */
public class RecipeFood implements java.io.Serializable {

	private RecipeFoodId id;
	private Food food;
	private Recipe recipe;
	private Float quantity;
	private String unity;

	public RecipeFood() {
	}

	public RecipeFood(RecipeFoodId id, Food food, Recipe recipe) {
		this.id = id;
		this.food = food;
		this.recipe = recipe;
	}

	public RecipeFood(RecipeFoodId id, Food food, Recipe recipe,
			Float quantity, String unity) {
		this.id = id;
		this.food = food;
		this.recipe = recipe;
		this.quantity = quantity;
		this.unity = unity;
	}

	public RecipeFoodId getId() {
		return this.id;
	}

	public void setId(RecipeFoodId id) {
		this.id = id;
	}

	public Food getFood() {
		return this.food;
	}

	public void setFood(Food food) {
		this.food = food;
	}

	public Recipe getRecipe() {
		return this.recipe;
	}

	public void setRecipe(Recipe recipe) {
		this.recipe = recipe;
	}

	public Float getQuantity() {
		return this.quantity;
	}

	public void setQuantity(Float quantity) {
		this.quantity = quantity;
	}

	public String getUnity() {
		return this.unity;
	}

	public void setUnity(String unity) {
		this.unity = unity;
	}

}
