package objects;

// Generated Jul 22, 2015 3:20:37 PM by Hibernate Tools 4.3.1

/**
 * RecipeFoodId generated by hbm2java
 */
public class RecipeFoodId implements java.io.Serializable {

	private int idFood;
	private int idRecipe;

	public RecipeFoodId() {
	}

	public RecipeFoodId(int idFood, int idRecipe) {
		this.idFood = idFood;
		this.idRecipe = idRecipe;
	}

	public int getIdFood() {
		return this.idFood;
	}

	public void setIdFood(int idFood) {
		this.idFood = idFood;
	}

	public int getIdRecipe() {
		return this.idRecipe;
	}

	public void setIdRecipe(int idRecipe) {
		this.idRecipe = idRecipe;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RecipeFoodId))
			return false;
		RecipeFoodId castOther = (RecipeFoodId) other;

		return (this.getIdFood() == castOther.getIdFood())
				&& (this.getIdRecipe() == castOther.getIdRecipe());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdFood();
		result = 37 * result + this.getIdRecipe();
		return result;
	}

}
