package objects;

// Generated Jul 8, 2015 3:09:09 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Refrigerator generated by hbm2java
 */
public class Refrigerator implements java.io.Serializable {

	private Integer idRefrigerator;
	private User user;
	private Set remainingFoods = new HashSet(0);

	public Refrigerator() {
	}

	public Refrigerator(User user) {
		this.user = user;
	}

	public Refrigerator(User user, Set remainingFoods) {
		this.user = user;
		this.remainingFoods = remainingFoods;
	}

	public Integer getIdRefrigerator() {
		return this.idRefrigerator;
	}

	public void setIdRefrigerator(Integer idRefrigerator) {
		this.idRefrigerator = idRefrigerator;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public Set getRemainingFoods() {
		return this.remainingFoods;
	}

	public void setRemainingFoods(Set remainingFoods) {
		this.remainingFoods = remainingFoods;
	}

}
