package objects;

// Generated Jul 17, 2015 12:09:18 PM by Hibernate Tools 4.3.1

/**
 * RefrigeratorId generated by hbm2java
 */
public class RefrigeratorId implements java.io.Serializable {

	private int idRefrigerator;
	private int idGroup;

	public RefrigeratorId() {
	}

	public RefrigeratorId(int idRefrigerator, int idGroup) {
		this.idRefrigerator = idRefrigerator;
		this.idGroup = idGroup;
	}

	public int getIdRefrigerator() {
		return this.idRefrigerator;
	}

	public void setIdRefrigerator(int idRefrigerator) {
		this.idRefrigerator = idRefrigerator;
	}

	public int getIdGroup() {
		return this.idGroup;
	}

	public void setIdGroup(int idGroup) {
		this.idGroup = idGroup;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RefrigeratorId))
			return false;
		RefrigeratorId castOther = (RefrigeratorId) other;

		return (this.getIdRefrigerator() == castOther.getIdRefrigerator())
				&& (this.getIdGroup() == castOther.getIdGroup());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdRefrigerator();
		result = 37 * result + this.getIdGroup();
		return result;
	}

}
