package objects;

// Generated Jul 17, 2015 7:51:51 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Refrigerator generated by hbm2java
 */
public class Refrigerator implements java.io.Serializable {

	private Integer idRefrigerator;
	private Group group;
	private Set remainingFoods = new HashSet(0);

	public Refrigerator() {
	}

	public Refrigerator(Group group) {
		this.group = group;
	}

	public Refrigerator(Group group, Set remainingFoods) {
		this.group = group;
		this.remainingFoods = remainingFoods;
	}

	public Integer getIdRefrigerator() {
		return this.idRefrigerator;
	}

	public void setIdRefrigerator(Integer idRefrigerator) {
		this.idRefrigerator = idRefrigerator;
	}

	public Group getGroup() {
		return this.group;
	}

	public void setGroup(Group group) {
		this.group = group;
	}

	public Set getRemainingFoods() {
		return this.remainingFoods;
	}

	public void setRemainingFoods(Set remainingFoods) {
		this.remainingFoods = remainingFoods;
	}

}
