package objects;
// default package
// Generated Jul 3, 2015 10:47:01 AM by Hibernate Tools 3.4.0.CR1

/**
 * RemainingFood generated by hbm2java
 */
public class RemainingFood implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5498553022566725121L;
	private RemainingFoodId id;
	private Refrigerator refrigerator;
	private Food food;
	private int quantity;
	private int minQuantity;

	public RemainingFood() {
	}

	public RemainingFood(RemainingFoodId id, Refrigerator refrigerator,
			Food food, int quantity, int minQuantity) {
		this.id = id;
		this.refrigerator = refrigerator;
		this.food = food;
		this.quantity = quantity;
		this.minQuantity = minQuantity;
	}

	public RemainingFoodId getId() {
		return this.id;
	}

	public void setId(RemainingFoodId id) {
		this.id = id;
	}

	public Refrigerator getRefrigerator() {
		return this.refrigerator;
	}

	public void setRefrigerator(Refrigerator refrigerator) {
		this.refrigerator = refrigerator;
	}

	public Food getFood() {
		return this.food;
	}

	public void setFood(Food food) {
		this.food = food;
	}

	public int getQuantity() {
		return this.quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

	public int getMinQuantity() {
		return this.minQuantity;
	}

	public void setMinQuantity(int minQuantity) {
		this.minQuantity = minQuantity;
	}

}
