package objects;
// default package
// Generated Jul 3, 2015 10:47:01 AM by Hibernate Tools 3.4.0.CR1

/**
 * RemainingFoodId generated by hbm2java
 */
public class RemainingFoodId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5175782779524231798L;
	private int idFood;
	private int idRefrigerator;

	public RemainingFoodId() {
	}

	public RemainingFoodId(int idFood, int idRefrigerator) {
		this.idFood = idFood;
		this.idRefrigerator = idRefrigerator;
	}

	public int getIdFood() {
		return this.idFood;
	}

	public void setIdFood(int idFood) {
		this.idFood = idFood;
	}

	public int getIdRefrigerator() {
		return this.idRefrigerator;
	}

	public void setIdRefrigerator(int idRefrigerator) {
		this.idRefrigerator = idRefrigerator;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RemainingFoodId))
			return false;
		RemainingFoodId castOther = (RemainingFoodId) other;

		return (this.getIdFood() == castOther.getIdFood())
				&& (this.getIdRefrigerator() == castOther.getIdRefrigerator());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdFood();
		result = 37 * result + this.getIdRefrigerator();
		return result;
	}

}
