package objects;

// Generated Jul 17, 2015 7:51:51 PM by Hibernate Tools 4.3.1

/**
 * RemainingFood generated by hbm2java
 */
public class RemainingFood implements java.io.Serializable {

	private RemainingFoodId id;
	private Refrigerator refrigerator;
	private int quantity;
	private int minQuantity;

	public RemainingFood() {
	}

	public RemainingFood(RemainingFoodId id, Refrigerator refrigerator,
			int quantity, int minQuantity) {
		this.id = id;
		this.refrigerator = refrigerator;
		this.quantity = quantity;
		this.minQuantity = minQuantity;
	}

	public RemainingFoodId getId() {
		return this.id;
	}

	public void setId(RemainingFoodId id) {
		this.id = id;
	}

	public Refrigerator getRefrigerator() {
		return this.refrigerator;
	}

	public void setRefrigerator(Refrigerator refrigerator) {
		this.refrigerator = refrigerator;
	}

	public int getQuantity() {
		return this.quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

	public int getMinQuantity() {
		return this.minQuantity;
	}

	public void setMinQuantity(int minQuantity) {
		this.minQuantity = minQuantity;
	}

}
