package objects;

// Generated Jul 17, 2015 12:09:18 PM by Hibernate Tools 4.3.1

/**
 * SharedNote generated by hbm2java
 */
public class SharedNote implements java.io.Serializable {

	private SharedNoteId id;
	private Note note;
	private User user;
	private int notReadYet;

	public SharedNote() {
	}

	public SharedNote(SharedNoteId id, Note note, User user, int notReadYet) {
		this.id = id;
		this.note = note;
		this.user = user;
		this.notReadYet = notReadYet;
	}

	public SharedNoteId getId() {
		return this.id;
	}

	public void setId(SharedNoteId id) {
		this.id = id;
	}

	public Note getNote() {
		return this.note;
	}

	public void setNote(Note note) {
		this.note = note;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public int getNotReadYet() {
		return this.notReadYet;
	}

	public void setNotReadYet(int notReadYet) {
		this.notReadYet = notReadYet;
	}

}
