package objects;
// default package
// Generated Jul 3, 2015 10:47:01 AM by Hibernate Tools 3.4.0.CR1

/**
 * SharedNotesId generated by hbm2java
 */
public class SharedNotesId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7273734321449332675L;
	private int idNote;
	private int idUser;

	public SharedNotesId() {
	}

	public SharedNotesId(int idNote, int idUser) {
		this.idNote = idNote;
		this.idUser = idUser;
	}

	public int getIdNote() {
		return this.idNote;
	}

	public void setIdNote(int idNote) {
		this.idNote = idNote;
	}

	public int getIdUser() {
		return this.idUser;
	}

	public void setIdUser(int idUser) {
		this.idUser = idUser;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SharedNotesId))
			return false;
		SharedNotesId castOther = (SharedNotesId) other;

		return (this.getIdNote() == castOther.getIdNote())
				&& (this.getIdUser() == castOther.getIdUser());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdNote();
		result = 37 * result + this.getIdUser();
		return result;
	}

}
