package objects;
// default package
// Generated Jul 3, 2015 10:47:01 AM by Hibernate Tools 3.4.0.CR1

/**
 * SharedNotesId generated by hbm2java
 */
public class SharedNotesId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7273734321449332675L;
	private int idNote;
	private int idUserCre;
	private int idUserRec;

	public SharedNotesId() {
	}

	public SharedNotesId(int idNote, int idUserCre, int idUserRec) {
		this.idNote = idNote;
		this.idUserCre = idUserCre;
		this.idUserRec = idUserRec;
		
	}

	public int getIdNote() {
		return this.idNote;
	}

	public void setIdNote(int idNote) {
		this.idNote = idNote;
	}


	public int getidUserCre() {
		return this.idUserCre;
	}

	public void setidUserCre(int idUser) {
		this.idUserCre = idUser;
	}
	
	
	public int getidUserRec() {
		return this.idUserRec;
	}

	public void setidUserRec(int idUser) {
		this.idUserRec = idUser;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SharedNotesId))
			return false;
		SharedNotesId castOther = (SharedNotesId) other;

		return (this.getIdNote() == castOther.getIdNote())
				&& (this.getidUserCre() == castOther.getidUserCre()
						&& this.getidUserRec() == castOther.getidUserRec());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdNote();
		result = 37 * result + this.getidUserCre();
		result = 37 * result + this.getidUserRec();
		return result;
	}

}
