package objects;

// Generated Jul 17, 2015 12:09:18 PM by Hibernate Tools 4.3.1

/**
 * SharedNote generated by hbm2java
 */
public class SharedNote implements java.io.Serializable {

	public static final String SHARED_NOTES_SENT = "shared_notes_sent";
	public static final String SHARED_NOTES_RECEIVED = "shared_not_received";
	public static final String SHARED_NOTES_REC_NOT_READ = "shared+notes_rec_not_read";
	public static final String NB_SHARED_NOTES_REC = "nb_shared_notes_rec";
	private SharedNoteId id;
	private Note note;
	private User user;
	private int notReadYet;

	public SharedNote() {
	}

	public SharedNote(SharedNoteId id, Note note, User user, int notReadYet) {
		this.id = id;
		this.note = note;
		this.user = user;
		this.notReadYet = notReadYet;
	}

	public SharedNoteId getId() {
		return this.id;
	}

	public void setId(SharedNoteId id) {
		this.id = id;
	}

	public Note getNote() {
		return this.note;
	}

	public void setNote(Note note) {
		this.note = note;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public int getNotReadYet() {
		return this.notReadYet;
	}

	public void setNotReadYet(int notReadYet) {
		this.notReadYet = notReadYet;
	}

}
