package objects;

// Generated Jul 8, 2015 2:25:51 PM by Hibernate Tools 4.3.1

/**
 * SharedNotes generated by hbm2java
 */
public class SharedNotes implements java.io.Serializable {

	private SharedNotesId id;
	private Note note;
	private User userByIdUserRec;
	private User userByIdUserCre;
	private Integer notReadYet;

	public SharedNotes() {
	}

	public SharedNotes(SharedNotesId id, Note note, User userByIdUserRec,
			User userByIdUserCre) {
		this.id = id;
		this.note = note;
		this.userByIdUserRec = userByIdUserRec;
		this.userByIdUserCre = userByIdUserCre;
	}

	public SharedNotes(SharedNotesId id, Note note, User userByIdUserRec,
			User userByIdUserCre, Integer notReadYet) {
		this.id = id;
		this.note = note;
		this.userByIdUserRec = userByIdUserRec;
		this.userByIdUserCre = userByIdUserCre;
		this.notReadYet = notReadYet;
	}

	public SharedNotesId getId() {
		return this.id;
	}

	public void setId(SharedNotesId id) {
		this.id = id;
	}

	public Note getNote() {
		return this.note;
	}

	public void setNote(Note note) {
		this.note = note;
	}

	public User getUserByIdUserRec() {
		return this.userByIdUserRec;
	}

	public void setUserByIdUserRec(User userByIdUserRec) {
		this.userByIdUserRec = userByIdUserRec;
	}

	public User getUserByIdUserCre() {
		return this.userByIdUserCre;
	}

	public void setUserByIdUserCre(User userByIdUserCre) {
		this.userByIdUserCre = userByIdUserCre;
	}

	public Integer getNotReadYet() {
		return this.notReadYet;
	}

	public void setNotReadYet(Integer notReadYet) {
		this.notReadYet = notReadYet;
	}

}
