package objects;

// Generated Jul 17, 2015 7:51:51 PM by Hibernate Tools 4.3.1

/**
 * SharedNoteId generated by hbm2java
 */
public class SharedNoteId implements java.io.Serializable {

	private int idNote;
	private int idUser;
	private int idGroup;

	public SharedNoteId() {
	}

	public SharedNoteId(int idNote, int idUser, int idGroup) {
		this.idNote = idNote;
		this.idUser = idUser;
		this.idGroup = idGroup;
	}

	public int getIdNote() {
		return this.idNote;
	}

	public void setIdNote(int idNote) {
		this.idNote = idNote;
	}

	public int getIdUser() {
		return this.idUser;
	}

	public void setIdUser(int idUser) {
		this.idUser = idUser;
	}

	public int getIdGroup() {
		return this.idGroup;
	}

	public void setIdGroup(int idGroup) {
		this.idGroup = idGroup;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SharedNoteId))
			return false;
		SharedNoteId castOther = (SharedNoteId) other;

		return (this.getIdNote() == castOther.getIdNote())
				&& (this.getIdUser() == castOther.getIdUser())
				&& (this.getIdGroup() == castOther.getIdGroup());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdNote();
		result = 37 * result + this.getIdUser();
		result = 37 * result + this.getIdGroup();
		return result;
	}

}
