package objects;

// Generated Jul 8, 2015 3:09:09 PM by Hibernate Tools 4.3.1

/**
 * SharedNoteId generated by hbm2java
 */
public class SharedNoteId implements java.io.Serializable {

	private int idUserRec;
	private int idUserCre;
	private int idNote;

	public SharedNoteId() {
	}

	public SharedNoteId(int idUserRec, int idUserCre, int idNote) {
		this.idUserRec = idUserRec;
		this.idUserCre = idUserCre;
		this.idNote = idNote;
	}

	public int getIdUserRec() {
		return this.idUserRec;
	}

	public void setIdUserRec(int idUserRec) {
		this.idUserRec = idUserRec;
	}

	public int getIdUserCre() {
		return this.idUserCre;
	}

	public void setIdUserCre(int idUserCre) {
		this.idUserCre = idUserCre;
	}

	public int getIdNote() {
		return this.idNote;
	}

	public void setIdNote(int idNote) {
		this.idNote = idNote;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SharedNoteId))
			return false;
		SharedNoteId castOther = (SharedNoteId) other;

		return (this.getIdUserRec() == castOther.getIdUserRec())
				&& (this.getIdUserCre() == castOther.getIdUserCre())
				&& (this.getIdNote() == castOther.getIdNote());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdUserRec();
		result = 37 * result + this.getIdUserCre();
		result = 37 * result + this.getIdNote();
		return result;
	}

}
