package objects;
// default package
// Generated Jul 3, 2015 10:47:01 AM by Hibernate Tools 3.4.0.CR1

/**
 * SharedNotes generated by hbm2java
 */
public class SharedNotes implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5717862943269062332L;
	private SharedNotesId id;
	private User user;
	private Note note;
	private Integer notReadYet;

	public SharedNotes() {
	}

	public SharedNotes(SharedNotesId id, User user, Note note) {
		this.id = id;
		this.user = user;
		this.note = note;
	}

	public SharedNotes(SharedNotesId id, User user, Note note,
			Integer notReadYet) {
		this.id = id;
		this.user = user;
		this.note = note;
		this.notReadYet = notReadYet;
	}

	public SharedNotesId getId() {
		return this.id;
	}

	public void setId(SharedNotesId id) {
		this.id = id;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public Note getNote() {
		return this.note;
	}

	public void setNote(Note note) {
		this.note = note;
	}

	public Integer getNotReadYet() {
		return this.notReadYet;
	}

	public void setNotReadYet(Integer notReadYet) {
		this.notReadYet = notReadYet;
	}

}
