package objects;

// Generated Jul 8, 2015 2:25:51 PM by Hibernate Tools 4.3.1

/**
 * SharedNotesId generated by hbm2java
 */
public class SharedNotesId implements java.io.Serializable {

	private int idNote;
	private int idUserCre;
	private int idUserRec;

	public SharedNotesId() {
	}

	public SharedNotesId(int idNote, int idUserCre, int idUserRec) {
		this.idNote = idNote;
		this.idUserCre = idUserCre;
		this.idUserRec = idUserRec;
	}

	public int getIdNote() {
		return this.idNote;
	}

	public void setIdNote(int idNote) {
		this.idNote = idNote;
	}

	public int getIdUserCre() {
		return this.idUserCre;
	}

	public void setIdUserCre(int idUserCre) {
		this.idUserCre = idUserCre;
	}

	public int getIdUserRec() {
		return this.idUserRec;
	}

	public void setIdUserRec(int idUserRec) {
		this.idUserRec = idUserRec;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SharedNotesId))
			return false;
		SharedNotesId castOther = (SharedNotesId) other;

		return (this.getIdNote() == castOther.getIdNote())
				&& (this.getIdUserCre() == castOther.getIdUserCre())
				&& (this.getIdUserRec() == castOther.getIdUserRec());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdNote();
		result = 37 * result + this.getIdUserCre();
		result = 37 * result + this.getIdUserRec();
		return result;
	}

}
