package objects;
// default package
// Generated Jul 3, 2015 10:47:01 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	
	public static final String USER_LBL_IN_SESSION = "userInfo"; 
	/**
	 * 
	 */
	private static final long serialVersionUID = 6510116175482654930L;
	private Integer idUser;
	private String FName;
	private String LName;
	private String mailAddress;
	private String password;
	private Date birthDate;
	private Set orders = new HashSet(0);
	private Set sharedNoteses = new HashSet(0);
	private Set refrigerators = new HashSet(0);

	public User() {
	}

	public User(String FName, String LName, String mailAddress, String password) {
		this.FName = FName;
		this.LName = LName;
		this.mailAddress = mailAddress;
		this.password = password;
	}

	public User(String FName, String LName, String mailAddress,
			String password, Date birthDate, Set orders, Set sharedNoteses,
			Set refrigerators) {
		this.FName = FName;
		this.LName = LName;
		this.mailAddress = mailAddress;
		this.password = password;
		this.birthDate = birthDate;
		this.orders = orders;
		this.sharedNoteses = sharedNoteses;
		this.refrigerators = refrigerators;
	}

	public Integer getIdUser() {
		return this.idUser;
	}

	public void setIdUser(Integer idUser) {
		this.idUser = idUser;
	}

	public String getFName() {
		return this.FName;
	}

	public void setFName(String FName) {
		this.FName = FName;
	}

	public String getLName() {
		return this.LName;
	}

	public void setLName(String LName) {
		this.LName = LName;
	}

	public String getMailAddress() {
		return this.mailAddress;
	}

	public void setMailAddress(String mailAddress) {
		this.mailAddress = mailAddress;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public Date getBirthDate() {
		return this.birthDate;
	}

	public void setBirthDate(Date birthDate) {
		this.birthDate = birthDate;
	}

	public Set getOrders() {
		return this.orders;
	}

	public void setOrders(Set orders) {
		this.orders = orders;
	}

	public Set getSharedNoteses() {
		return this.sharedNoteses;
	}

	public void setSharedNoteses(Set sharedNoteses) {
		this.sharedNoteses = sharedNoteses;
	}

	public Set getRefrigerators() {
		return this.refrigerators;
	}

	public void setRefrigerators(Set refrigerators) {
		this.refrigerators = refrigerators;
	}

}
